// resources.ts can be generated by "npm run toc"
import resources from "./resources.ts";

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: "common";
    resources: typeof resources;
  }
}
